# app/models.py

from .database import db
from sqlalchemy import String, Integer, Float, DateTime, Boolean, Text

class Reseller(db.Model):
    __tablename__ = 'reseller' # Pastikan nama tabel ini sama dengan di SQL Server Anda

    kode = db.Column(String(50), primary_key=True)
    nama = db.Column(String(255))
    saldo = db.Column(Float)
    alamat = db.Column(String(500))
    pin = db.Column(String(10))
    aktif = db.Column(Integer)
    kode_upline = db.Column(String(50), nullable=True)
    kode_level = db.Column(String(10))
    keterangan = db.Column(String(255), nullable=True)
    tgl_daftar = db.Column(DateTime)
    saldo_minimal = db.Column(Float)
    tgl_aktivitas = db.Column(DateTime, nullable=True)
    pengingat_saldo = db.Column(Float)
    f_pengingat_saldo = db.Column(Integer)
    nama_pemilik = db.Column(String(255), nullable=True)
    kode_area = db.Column(String(50), nullable=True)
    tgl_pengingat_saldo = db.Column(DateTime, nullable=True)
    markup = db.Column(Float)
    oid = db.Column(String(50), nullable=True)
    poin = db.Column(Integer)
    alamat_ip = db.Column(String(100), nullable=True)
    password_ip = db.Column(String(100), nullable=True)
    url_report = db.Column(String(255), nullable=True)
    tgl_data = db.Column(DateTime)
    wrkirim = db.Column(Integer)
    suspend = db.Column(Integer, nullable=True)
    kode_deposit = db.Column(String(50), nullable=True)
    berita_transfer = db.Column(String(255), nullable=True)
    ip_no_sign = db.Column(String(100), nullable=True)
    deleted = db.Column(Integer, nullable=True)
    nomor_ktp = db.Column(String(50), nullable=True)
    npwp = db.Column(String(50), nullable=True)
    harus_ubah_pin = db.Column(Integer, nullable=True)
    nomor_hp = db.Column(String(50), nullable=True)
    email = db.Column(String(100), nullable=True)
    blok_produk = db.Column(Text, nullable=True)
    kode_referral = db.Column(String(50), nullable=True)
    komisi = db.Column(Float, nullable=True)
    wrgkirim = db.Column(Integer, nullable=True)


class Transaksi(db.Model):
    __tablename__ = 'transaksi' # Pastikan nama tabel ini sama dengan di SQL Server Anda

    kode = db.Column(Integer, primary_key=True)
    tgl_entri = db.Column(DateTime)
    kode_produk = db.Column(String(50))
    tujuan = db.Column(String(100))
    kode_reseller = db.Column(String(50), db.ForeignKey('reseller.kode'))
    pengirim = db.Column(String(100))
    tipe_pengirim = db.Column(String(5))
    harga = db.Column(Float)
    kode_inbox = db.Column(Integer)
    status = db.Column(Integer)
    tgl_status = db.Column(DateTime)
    kode_modul = db.Column(Integer)
    kode_terminal = db.Column(String(50), nullable=True)
    ket_modul = db.Column(String(500), nullable=True)
    harga_beli = db.Column(Float)
    kode_jawaban = db.Column(Integer)
    saldo_awal = db.Column(Float)
    perintah = db.Column(Text)
    counter = db.Column(Integer)
    counter2 = db.Column(Integer)
    sn = db.Column(String(500), nullable=True)
    modul_proses = db.Column(String(50))
    kirim_ulang = db.Column(String(50))
    penerima = db.Column(String(100), nullable=True)
    qty = db.Column(Integer)
    kirim_info = db.Column(Integer)
    kode_area = db.Column(String(50), nullable=True)
    ref_id = db.Column(String(100), nullable=True)
    params = db.Column(Text, nullable=True)
    harga_beli2 = db.Column(Float, nullable=True)
    is_voucher = db.Column(Integer, nullable=True)
    komisi = db.Column(Float, nullable=True)
    bill_set = db.Column(String(255), nullable=True)
    bill = db.Column(String(255), nullable=True)
    keterangan = db.Column(String(255), nullable=True)
    poin = db.Column(Integer, nullable=True)
    wrkirim = db.Column(Integer, nullable=True)
    hide_kiosk = db.Column(Integer, nullable=True)
    unit = db.Column(Integer, nullable=True)
    saldo_supplier = db.Column(Float, nullable=True)
    kode_dompet = db.Column(String(50), nullable=True)