"""empty message

Revision ID: 6587f61d3943
Revises: 
Create Date: 2025-08-26 16:47:07.318984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6587f61d3943'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reseller',
    sa.Column('kode', sa.String(length=50), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=True),
    sa.Column('saldo', sa.Float(), nullable=True),
    sa.Column('alamat', sa.String(length=500), nullable=True),
    sa.Column('pin', sa.String(length=10), nullable=True),
    sa.Column('aktif', sa.Integer(), nullable=True),
    sa.Column('kode_upline', sa.String(length=50), nullable=True),
    sa.Column('kode_level', sa.String(length=10), nullable=True),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('tgl_daftar', sa.DateTime(), nullable=True),
    sa.Column('saldo_minimal', sa.Float(), nullable=True),
    sa.Column('tgl_aktivitas', sa.DateTime(), nullable=True),
    sa.Column('pengingat_saldo', sa.Float(), nullable=True),
    sa.Column('f_pengingat_saldo', sa.Integer(), nullable=True),
    sa.Column('nama_pemilik', sa.String(length=255), nullable=True),
    sa.Column('kode_area', sa.String(length=50), nullable=True),
    sa.Column('tgl_pengingat_saldo', sa.DateTime(), nullable=True),
    sa.Column('markup', sa.Float(), nullable=True),
    sa.Column('oid', sa.String(length=50), nullable=True),
    sa.Column('poin', sa.Integer(), nullable=True),
    sa.Column('alamat_ip', sa.String(length=100), nullable=True),
    sa.Column('password_ip', sa.String(length=100), nullable=True),
    sa.Column('url_report', sa.String(length=255), nullable=True),
    sa.Column('tgl_data', sa.DateTime(), nullable=True),
    sa.Column('wrkirim', sa.Integer(), nullable=True),
    sa.Column('suspend', sa.Integer(), nullable=True),
    sa.Column('kode_deposit', sa.String(length=50), nullable=True),
    sa.Column('berita_transfer', sa.String(length=255), nullable=True),
    sa.Column('ip_no_sign', sa.String(length=100), nullable=True),
    sa.Column('deleted', sa.Integer(), nullable=True),
    sa.Column('nomor_ktp', sa.String(length=50), nullable=True),
    sa.Column('npwp', sa.String(length=50), nullable=True),
    sa.Column('harus_ubah_pin', sa.Integer(), nullable=True),
    sa.Column('nomor_hp', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('blok_produk', sa.Text(), nullable=True),
    sa.Column('kode_referral', sa.String(length=50), nullable=True),
    sa.Column('komisi', sa.Float(), nullable=True),
    sa.Column('wrgkirim', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('kode')
    )
    op.create_table('transaksi',
    sa.Column('kode', sa.Integer(), nullable=False),
    sa.Column('tgl_entri', sa.DateTime(), nullable=True),
    sa.Column('kode_produk', sa.String(length=50), nullable=True),
    sa.Column('tujuan', sa.String(length=100), nullable=True),
    sa.Column('kode_reseller', sa.String(length=50), nullable=True),
    sa.Column('pengirim', sa.String(length=100), nullable=True),
    sa.Column('tipe_pengirim', sa.String(length=5), nullable=True),
    sa.Column('harga', sa.Float(), nullable=True),
    sa.Column('kode_inbox', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('tgl_status', sa.DateTime(), nullable=True),
    sa.Column('kode_modul', sa.Integer(), nullable=True),
    sa.Column('kode_terminal', sa.String(length=50), nullable=True),
    sa.Column('ket_modul', sa.String(length=500), nullable=True),
    sa.Column('harga_beli', sa.Float(), nullable=True),
    sa.Column('kode_jawaban', sa.Integer(), nullable=True),
    sa.Column('saldo_awal', sa.Float(), nullable=True),
    sa.Column('perintah', sa.Text(), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.Column('counter2', sa.Integer(), nullable=True),
    sa.Column('sn', sa.String(length=500), nullable=True),
    sa.Column('modul_proses', sa.String(length=50), nullable=True),
    sa.Column('kirim_ulang', sa.String(length=50), nullable=True),
    sa.Column('penerima', sa.String(length=100), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('kirim_info', sa.Integer(), nullable=True),
    sa.Column('kode_area', sa.String(length=50), nullable=True),
    sa.Column('ref_id', sa.String(length=100), nullable=True),
    sa.Column('params', sa.Text(), nullable=True),
    sa.Column('harga_beli2', sa.Float(), nullable=True),
    sa.Column('is_voucher', sa.Integer(), nullable=True),
    sa.Column('komisi', sa.Float(), nullable=True),
    sa.Column('bill_set', sa.String(length=255), nullable=True),
    sa.Column('bill', sa.String(length=255), nullable=True),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('poin', sa.Integer(), nullable=True),
    sa.Column('wrkirim', sa.Integer(), nullable=True),
    sa.Column('hide_kiosk', sa.Integer(), nullable=True),
    sa.Column('unit', sa.Integer(), nullable=True),
    sa.Column('saldo_supplier', sa.Float(), nullable=True),
    sa.Column('kode_dompet', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['kode_reseller'], ['reseller.kode'], ),
    sa.PrimaryKeyConstraint('kode')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaksi')
    op.drop_table('reseller')
    # ### end Alembic commands ###
