"""empty message

Revision ID: 8212901f9db0
Revises: 
Create Date: 2025-08-23 08:59:54.566628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8212901f9db0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reseller',
    sa.Column('kode', sa.String(length=50), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('saldo', sa.BigInteger(), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('pin', sa.String(length=10), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('kode_upline', sa.String(length=50), nullable=True),
    sa.Column('kode_level', sa.String(length=10), nullable=True),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('tgl_daftar', sa.DateTime(), nullable=True),
    sa.Column('saldo_minimal', sa.BigInteger(), nullable=True),
    sa.Column('tgl_aktivitas', sa.DateTime(), nullable=True),
    sa.Column('pengingat_saldo', sa.BigInteger(), nullable=True),
    sa.Column('f_pengingat_saldo', sa.Boolean(), nullable=True),
    sa.Column('nama_pemilik', sa.String(length=100), nullable=True),
    sa.Column('kode_area', sa.String(length=10), nullable=True),
    sa.Column('tgl_pengingat', sa.DateTime(), nullable=True),
    sa.Column('markup', sa.Integer(), nullable=True),
    sa.Column('old', sa.String(length=50), nullable=True),
    sa.Column('poin', sa.Integer(), nullable=True),
    sa.Column('alamat_ip', sa.String(length=45), nullable=True),
    sa.Column('url_report', sa.String(length=255), nullable=True),
    sa.Column('tgl_data', sa.DateTime(), nullable=True),
    sa.Column('wrkirim', sa.String(length=50), nullable=True),
    sa.Column('suspemd', sa.Boolean(), nullable=True),
    sa.Column('kode_deposit', sa.String(length=50), nullable=True),
    sa.Column('berita_transfer', sa.Text(), nullable=True),
    sa.Column('ip_no_sign', sa.String(length=45), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('nomor_ktp', sa.String(length=20), nullable=True),
    sa.Column('npwp', sa.String(length=20), nullable=True),
    sa.Column('harus_ubah_pin', sa.Boolean(), nullable=True),
    sa.Column('nomor_hp', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('blok_produk', sa.Text(), nullable=True),
    sa.Column('kode_referal', sa.String(length=50), nullable=True),
    sa.Column('komisi', sa.BigInteger(), nullable=True),
    sa.Column('wrgkirim', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('kode')
    )
    op.create_table('transaksi',
    sa.Column('kode', sa.String(length=50), nullable=False),
    sa.Column('tgl_entri', sa.DateTime(), nullable=True),
    sa.Column('kode_produk', sa.String(length=50), nullable=True),
    sa.Column('tujuan', sa.String(length=50), nullable=True),
    sa.Column('kode_reseller', sa.String(length=50), nullable=False),
    sa.Column('pengirim', sa.String(length=50), nullable=True),
    sa.Column('tipe_pengirim', sa.String(length=20), nullable=True),
    sa.Column('harga', sa.BigInteger(), nullable=False),
    sa.Column('kode_inbox', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tgl_status', sa.DateTime(), nullable=True),
    sa.Column('kode_terminal', sa.String(length=50), nullable=True),
    sa.Column('ket_modul', sa.Text(), nullable=True),
    sa.Column('harga_beli', sa.BigInteger(), nullable=True),
    sa.Column('kode_jawaban', sa.String(length=50), nullable=True),
    sa.Column('saldo_awal', sa.BigInteger(), nullable=True),
    sa.Column('perintah', sa.Text(), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.Column('counter2', sa.Integer(), nullable=True),
    sa.Column('sn', sa.String(length=100), nullable=True),
    sa.Column('modul_proses', sa.String(length=50), nullable=True),
    sa.Column('kirim_ulang', sa.Boolean(), nullable=True),
    sa.Column('penerima', sa.String(length=100), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('is_voucher', sa.Boolean(), nullable=True),
    sa.Column('komisi', sa.BigInteger(), nullable=True),
    sa.Column('bill_set', sa.String(length=50), nullable=True),
    sa.Column('keterangan', sa.Text(), nullable=True),
    sa.Column('poin', sa.Integer(), nullable=True),
    sa.Column('wrkirim', sa.String(length=50), nullable=True),
    sa.Column('hide_kiosk', sa.Boolean(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('saldo_supplier', sa.BigInteger(), nullable=True),
    sa.Column('kode_dompet', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['kode_reseller'], ['reseller.kode'], ),
    sa.PrimaryKeyConstraint('kode')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaksi')
    op.drop_table('reseller')
    # ### end Alembic commands ###
