"""Initial database models

Revision ID: d783f77c2c88
Revises: 
Create Date: 2025-08-22 17:45:22.913386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd783f77c2c88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kode_insentif',
    sa.Column('id_insentif', sa.String(length=50), nullable=False),
    sa.Column('kode', sa.String(length=50), nullable=True),
    sa.Column('persentase', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id_insentif')
    )
    op.create_table('kondisi_outlet',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('kondisi', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id_mr', sa.String(length=50), nullable=False),
    sa.Column('nama_mr', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_mr')
    )
    op.create_table('outlet',
    sa.Column('id_tm', sa.String(length=50), nullable=False),
    sa.Column('nama_tm', sa.String(length=100), nullable=True),
    sa.Column('id_kondisi_outlet', sa.String(length=50), nullable=True),
    sa.Column('lokasi', sa.String(length=255), nullable=True),
    sa.Column('id_mr', sa.String(length=50), nullable=True),
    sa.Column('transaksi', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_kondisi_outlet'], ['kondisi_outlet.id'], ),
    sa.ForeignKeyConstraint(['id_mr'], ['sales.id_mr'], ),
    sa.PrimaryKeyConstraint('id_tm')
    )
    op.create_table('report_transaksi',
    sa.Column('id_trx', sa.String(length=50), nullable=False),
    sa.Column('id_mr', sa.String(length=50), nullable=True),
    sa.Column('id_tm', sa.String(length=50), nullable=True),
    sa.Column('transaksi', sa.BigInteger(), nullable=False),
    sa.Column('create_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id_mr'], ['sales.id_mr'], ),
    sa.ForeignKeyConstraint(['id_tm'], ['outlet.id_tm'], ),
    sa.PrimaryKeyConstraint('id_trx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_transaksi')
    op.drop_table('outlet')
    op.drop_table('sales')
    op.drop_table('kondisi_outlet')
    op.drop_table('kode_insentif')
    # ### end Alembic commands ###
