"""empty message

Revision ID: fe1d8d899d84
Revises: e23ae29e7a8b
Create Date: 2025-08-24 10:45:32.338123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe1d8d899d84'
down_revision = 'e23ae29e7a8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reseller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tgl_pengingat_saldo', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('oid', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('password_ip', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('suspend', sa.Boolean(), nullable=True))
        batch_op.drop_column('old')
        batch_op.drop_column('tgl_pengingat')
        batch_op.drop_column('suspemd')

    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kirim_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('kode_area', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('ref_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('params', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('harga_beli2', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.drop_column('harga_beli2')
        batch_op.drop_column('params')
        batch_op.drop_column('ref_id')
        batch_op.drop_column('kode_area')
        batch_op.drop_column('kirim_info')

    with op.batch_alter_table('reseller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suspemd', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tgl_pengingat', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('old', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('suspend')
        batch_op.drop_column('password_ip')
        batch_op.drop_column('oid')
        batch_op.drop_column('tgl_pengingat_saldo')

    # ### end Alembic commands ###
